export const PROVIDER_PRESETS = [
  {
    id: 'hawk-builtin',
    name: '🦅 Hawk 内置 AI',
    emoji: '🦅',
    baseUrl: '', // 运行时从 defaults.js 获取
    apiKey: '',
    models: ['gemma-4-31b-it'],
    note: 'App 提供的默认模型，已包含限速保护，无需配置 API Key。',
    isBuiltin: true,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    emoji: '🟠',
    baseUrl: 'https://api.deepseek.com/v1',
    apiKey: '',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    note: '国内性价比最高的大模型。',
    isBuiltin: false,
  },
  {
    id: 'qwen',
    name: 'Qwen (通义千问)',
    emoji: '🟣',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    apiKey: '',
    models: ['qwen-vl-plus', 'qwen-vl-max', 'qwen-max'],
    note: '阿里出品，多模态识别能力强。',
    isBuiltin: false,
  },
  {
    id: 'gemini',
    name: 'Gemini (Google)',
    emoji: '🔵',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    apiKey: '',
    models: ['gemini-2.0-flash', 'gemini-1.5-pro'],
    note: 'Google 旗舰模型，支持超大上下文和图片识别。',
    isBuiltin: false,
  },
  {
    id: 'longcat',
    name: 'LongCat',
    emoji: '🐱',
    baseUrl: 'https://api.longcat.chat/openai/v1',
    apiKey: '',
    models: ['LongCat-Flash-Chat'],
    note: '快速、稳定的中转服务。',
    isBuiltin: false,
  },
  {
    id: 'kimi',
    name: 'Kimi (月之暗面)',
    emoji: '🌙',
    baseUrl: 'https://api.moonshot.cn/v1',
    apiKey: '',
    models: ['moonshot-v1-8k', 'moonshot-v1-32k'],
    note: '长文本专家。',
    isBuiltin: false,
  },
  {
    id: 'zhipu',
    name: 'GLM (智谱清言)',
    emoji: '🟢',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    apiKey: '',
    models: ['glm-4v', 'glm-4'],
    note: '清华系背景，国产领先。',
    isBuiltin: false,
  },
  {
    id: 'minimax',
    name: 'MiniMax (稀宇)',
    emoji: '🎵',
    baseUrl: 'https://api.minimax.chat/v1',
    apiKey: '',
    models: ['abab6.5-chat', 'abab7-preview'],
    note: '擅长角色扮演和情感表达。',
    isBuiltin: false,
  },
  {
    id: 'doubao',
    name: 'Doubao (豆包)',
    emoji: '🔴',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    apiKey: '',
    models: ['ep-xxxxxx'],
    note: '字节跳动出品。注意：模型名处请填写您的 Endpoint ID。',
    isBuiltin: false,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    emoji: '⚪',
    baseUrl: 'https://api.openai.com/v1',
    apiKey: '',
    models: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-vision-preview'],
    note: '行业标准。',
    isBuiltin: false,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    emoji: '🌐',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKey: '',
    models: ['openrouter/auto', 'anthropic/claude-3.5-sonnet'],
    note: '聚合全球主流模型。',
    isBuiltin: false,
  },
  {
    id: 'grok',
    name: 'Grok (xAI)',
    emoji: '❌',
    baseUrl: 'https://api.x.ai/v1',
    apiKey: '',
    models: ['grok-3', 'grok-vision-beta'],
    note: '马斯克出品。',
    isBuiltin: false,
  },
  {
    id: 'nvidia',
    name: 'Nvidia Build',
    emoji: '🟩',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    apiKey: '',
    models: ['meta/llama-3.1-70b-instruct'],
    note: '英伟达提供的免费/付费推理服务。',
    isBuiltin: false,
  },
  {
    id: 'siliconflow',
    name: '硅基流动 (SiliconFlow)',
    emoji: '📱',
    baseUrl: 'https://api.siliconflow.cn/v1',
    apiKey: '',
    models: ['Qwen/Qwen2.5-7B-Instruct', 'deepseek-ai/DeepSeek-V2.5'],
    note: '支持小米 MiMo 等国内外主流模型。',
    isBuiltin: false,
  },
  {
    id: 'custom',
    name: '自定义',
    emoji: '⚙️',
    baseUrl: '',
    apiKey: '',
    models: [],
    note: '配置您自己的任意 OpenAI 兼容 API。',
    isBuiltin: false,
  }
];
